import { Type } from '@feathersjs/typebox'

export const physicalProperties: string[] = [
  'density',
  'compressive_strength',
  'tensile_strength',
  'youngs_modulus',
  'shrinkage',
  'settlement',
  'thermal_conductivity',
  'thermal_capacity',
  'vapor_diffusion_resistance',
  'moisture_buffering',
  'u',
  'effusivity',
  'diffusivity',
  'absorption_coefficient',
  'sound_reduction_index',
  'reaction_to_fire',
  'building_material_class',
  'fire_resistance_class',
  'air_tightness'
]

export const allPhysicalProperties: string[] = [
  ...physicalProperties,
  ...physicalProperties.map((p) => `${p}_low`),
  ...physicalProperties.map((p) => `${p}_high`)
]

export const allPhysicalPropertiesSchema = {
  density: Type.Optional(Type.Union([Type.Null(), Type.Number()])),
  compressive_strength: Type.Optional(Type.Union([Type.Null(), Type.Number()])),
  tensile_strength: Type.Optional(Type.Union([Type.Null(), Type.Number()])),
  youngs_modulus: Type.Optional(Type.Union([Type.Null(), Type.Number()])),
  shrinkage: Type.Optional(Type.Union([Type.Null(), Type.Number()])),
  settlement: Type.Optional(Type.Union([Type.Null(), Type.Number()])),
  thermal_conductivity: Type.Optional(Type.Union([Type.Null(), Type.Number()])),
  thermal_capacity: Type.Optional(Type.Union([Type.Null(), Type.Number()])),
  vapor_diffusion_resistance: Type.Optional(Type.Union([Type.Null(), Type.Number()])),
  moisture_buffering: Type.Optional(Type.Union([Type.Null(), Type.Number()])),
  u: Type.Optional(Type.Union([Type.Null(), Type.Number()])),
  effusivity: Type.Optional(Type.Union([Type.Null(), Type.Number()])),
  diffusivity: Type.Optional(Type.Union([Type.Null(), Type.Number()])),
  absorption_coefficient: Type.Optional(Type.Union([Type.Null(), Type.Number()])),
  sound_reduction_index: Type.Optional(Type.Union([Type.Null(), Type.Number()])),
  reaction_to_fire: Type.Optional(Type.Union([Type.Null(), Type.Number()])),
  building_material_class: Type.Optional(Type.Union([Type.Null(), Type.Number()])),
  fire_resistance_class: Type.Optional(Type.Union([Type.Null(), Type.Number()])),
  air_tightness: Type.Optional(Type.Union([Type.Null(), Type.Number()])),

  density_low: Type.Optional(Type.Union([Type.Null(), Type.Number()])),
  compressive_strength_low: Type.Optional(Type.Union([Type.Null(), Type.Number()])),
  tensile_strength_low: Type.Optional(Type.Union([Type.Null(), Type.Number()])),
  youngs_modulus_low: Type.Optional(Type.Union([Type.Null(), Type.Number()])),
  shrinkage_low: Type.Optional(Type.Union([Type.Null(), Type.Number()])),
  settlement_low: Type.Optional(Type.Union([Type.Null(), Type.Number()])),
  thermal_conductivity_low: Type.Optional(Type.Union([Type.Null(), Type.Number()])),
  thermal_capacity_low: Type.Optional(Type.Union([Type.Null(), Type.Number()])),
  vapor_diffusion_resistance_low: Type.Optional(Type.Union([Type.Null(), Type.Number()])),
  moisture_buffering_low: Type.Optional(Type.Union([Type.Null(), Type.Number()])),
  u_low: Type.Optional(Type.Union([Type.Null(), Type.Number()])),
  effusivity_low: Type.Optional(Type.Union([Type.Null(), Type.Number()])),
  diffusivity_low: Type.Optional(Type.Union([Type.Null(), Type.Number()])),
  absorption_coefficient_low: Type.Optional(Type.Union([Type.Null(), Type.Number()])),
  sound_reduction_index_low: Type.Optional(Type.Union([Type.Null(), Type.Number()])),
  reaction_to_fire_low: Type.Optional(Type.Union([Type.Null(), Type.Number()])),
  building_material_class_low: Type.Optional(Type.Union([Type.Null(), Type.Number()])),
  fire_resistance_class_low: Type.Optional(Type.Union([Type.Null(), Type.Number()])),
  air_tightness_low: Type.Optional(Type.Union([Type.Null(), Type.Number()])),

  density_high: Type.Optional(Type.Union([Type.Null(), Type.Number()])),
  compressive_strength_high: Type.Optional(Type.Union([Type.Null(), Type.Number()])),
  tensile_strength_high: Type.Optional(Type.Union([Type.Null(), Type.Number()])),
  youngs_modulus_high: Type.Optional(Type.Union([Type.Null(), Type.Number()])),
  shrinkage_high: Type.Optional(Type.Union([Type.Null(), Type.Number()])),
  settlement_high: Type.Optional(Type.Union([Type.Null(), Type.Number()])),
  thermal_conductivity_high: Type.Optional(Type.Union([Type.Null(), Type.Number()])),
  thermal_capacity_high: Type.Optional(Type.Union([Type.Null(), Type.Number()])),
  vapor_diffusion_resistance_high: Type.Optional(Type.Union([Type.Null(), Type.Number()])),
  moisture_buffering_high: Type.Optional(Type.Union([Type.Null(), Type.Number()])),
  u_high: Type.Optional(Type.Union([Type.Null(), Type.Number()])),
  effusivity_high: Type.Optional(Type.Union([Type.Null(), Type.Number()])),
  diffusivity_high: Type.Optional(Type.Union([Type.Null(), Type.Number()])),
  absorption_coefficient_high: Type.Optional(Type.Union([Type.Null(), Type.Number()])),
  sound_reduction_index_high: Type.Optional(Type.Union([Type.Null(), Type.Number()])),
  reaction_to_fire_high: Type.Optional(Type.Union([Type.Null(), Type.Number()])),
  building_material_class_high: Type.Optional(Type.Union([Type.Null(), Type.Number()])),
  fire_resistance_class_high: Type.Optional(Type.Union([Type.Null(), Type.Number()])),
  air_tightness_high: Type.Optional(Type.Union([Type.Null(), Type.Number()])),
}