// For more information about this file see https://dove.feathersjs.com/guides/cli/service.html
import { authenticate } from '@feathersjs/authentication'

import { hooks as schemaHooks } from '@feathersjs/schema'

import {
  userDataValidator,
  userPatchValidator,
  userQueryValidator,
  userResolver,
  userExternalResolver,
  userDataResolver,
  userPatchResolver,
  userQueryResolver,
  userDataSchema,
  userPatchSchema,
  userQuerySchema,
  userSchema,
  generateFake
} from './users.schema'

import type { Application, NextFunction } from '../../declarations'
import { UserService, getOptions } from './users.class'
import { userPath, userMethods } from './users.shared'
import { createSwaggerServiceOptions } from 'feathers-swagger'
import { logger } from '../../logger'

export * from './users.class'
export * from './users.schema'

export const userIterations = 30
// A configure function that registers the service and its hooks via `app.configure`
export const user = (app: Application) => {
  // Register our service on the Feathers application
  app.use(userPath, new UserService(getOptions(app)), {
    // A list of all methods this service exposes externally
    methods: userMethods,
    // You can add additional custom events to be sent to clients here
    events: [],

    docs: createSwaggerServiceOptions({
      schemas: { userSchema, userDataSchema, userPatchSchema, userQuerySchema },
      docs: {
        // any options for service.docs can be added here
        securities: ['find', 'get', 'patch', 'remove']
      }
    }),
    createFake: async () => {
      const fakeData = await generateFake()
      logger.info(`fake data generated: ${JSON.stringify(fakeData)}`)
      const fakeDataCreatedByService = await app.service(userPath).create(fakeData, {})
      logger.info(`data generated by service: ${JSON.stringify(fakeDataCreatedByService)}`)
      return fakeDataCreatedByService
    },
    fakerOptions: {
      iterations: userIterations
    }
  })
  // Initialize hooks
  app.service(userPath).hooks({
    around: {
      all: [schemaHooks.resolveExternal(userExternalResolver), schemaHooks.resolveResult(userResolver)],
      find: [authenticate('jwt')],
      get: [authenticate('jwt')],
      create: [],
      update: [authenticate('jwt')],
      patch: [authenticate('jwt')],
      remove: [authenticate('jwt')]
    },
    before: {
      all: [schemaHooks.validateQuery(userQueryValidator), schemaHooks.resolveQuery(userQueryResolver)],
      find: [],
      get: [],
      create: [schemaHooks.validateData(userDataValidator), schemaHooks.resolveData(userDataResolver)],
      patch: [schemaHooks.validateData(userPatchValidator), schemaHooks.resolveData(userPatchResolver)],
      remove: []
    },
    after: {
      all: []
    },
    error: {
      all: []
    }
  })
}

// Add this service to the service type index
declare module '../../declarations' {
  interface ServiceTypes {
    [userPath]: UserService
  }
}
