/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    CircleMapInput: typeof import('./src/components/CircleMapInput.vue')['default']
    MapLibreMap: typeof import('./src/components/MapLibreMap.vue')['default']
    PolygonsMapInput: typeof import('./src/components/PolygonsMapInput.vue')['default']
    ResourcesCard: typeof import('./src/components/ResourcesCard.vue')['default']
    ResourcesTable: typeof import('./src/components/ResourcesTable.vue')['default']
    RootNavigationDrawer: typeof import('./src/components/RootNavigationDrawer.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TheCounter: typeof import('./src/components/TheCounter.vue')['default']
    TheFooter: typeof import('./src/components/TheFooter.vue')['default']
    TheInput: typeof import('./src/components/TheInput.vue')['default']
    WebMap: typeof import('./src/components/WebMap.vue')['default']
  }
}
