// Use DBML to define your database structure
// Docs: https://dbml.dbdiagram.io/docs

Table NaturalResource {
  id int [pk]
}

Table BuildingMaterial {
  id int [pk]
}

Table TechnicalConstruction {
  id int [pk]
}

Table Building {
  id int [pk]
}

Table Professional {
  id int [pk]
}

Table BuildingElement {
  id int [pk]
  technical_construction_id int [ref: > TechnicalConstruction.id]
  building_id int [ref: > Building.id]
}

Table BuildingMaterial_NaturalResource {
  natural_resource_id int [ref: > NaturalResource.id]
  building_material_id int [ref: > BuildingMaterial.id]
}

Table TechnicalConstruction_BuildingMaterial {
  building_material_id int [ref: > BuildingMaterial.id]
  technical_construction_id int [ref: > TechnicalConstruction.id]
}

Table BuildingElement_Professional {
  building_element_id int [ref: > BuildingElement.id]
  professional_id int [ref: > Professional.id]
}

Table Building_BuildingMaterial {
  building_material_id int [ref: > BuildingMaterial.id]
  building_id int [ref: > Building.id]
}

Table Professional_Building {
  building_id int [ref: > Building.id]
  professional_id int [ref: > Professional.id]
}

Table Professional_BuildingMaterial {
  building_material_id int [ref: > BuildingMaterial.id]
  professional_id int [ref: > Professional.id]
}

Table Professional_TechnicalConstruction {
  technical_construction_id int [ref: > TechnicalConstruction.id]
  professional_id int [ref: > Professional.id]
}
