version: '3.9'
services:
  backend:
    image: ghcr.io/epfl-enac/alice-ethz-arema-backend:latest.yml
    build: !reset null
    restart: always
  s3_server:
    image: ghcr.io/epfl-enac/alice-ethz-arema-s3_server:latest.yml
    build: !reset null
    restart: always
  uploadfastapi:
    image: ghcr.io/epfl-enac/alice-ethz-arema-uploadfastapi:latest.yml
    build: !reset null
    restart: always
  admin:
    image: ghcr.io/epfl-enac/alice-ethz-arema-admin:latest.yml
    build: !reset null
    restart: always
  frontend:
    image: ghcr.io/epfl-enac/alice-ethz-arema-frontend:latest.yml
    build: !reset null
    restart: always
