// // For more information about this file see https://dove.feathersjs.com/guides/cli/service.schemas.html
import { resolve, virtual } from '@feathersjs/schema'
import { Type, getValidator, querySyntax } from '@feathersjs/typebox'
import type { Static } from '@feathersjs/typebox'
import { User, userSchema } from '../users/users.schema'

import type { HookContext } from '../../declarations'
import { dataValidator, queryValidator } from '../../validators'
import { faker } from '@faker-js/faker'
import { logger } from '../../logger'

// Main data model schema
export const naturalResourceSchema = Type.Object(
  {
    id: Type.Number(),
    name: Type.String(),
    zone: Type.String(), // "wsg84",
    dimension: Type.String(),
    amount: Type.Number(),
    images: Type.Array(Type.String()), // url
    description: Type.String(),

    // generated by the resolver
    // professionals: Type.Array(Type.Ref(professionalSchema)),
    // technicalConstructions:  Type.Array(Type.Ref(technicalConstructionSchema)),
    // updatedByUser: Type.Ref(userSchema),
    // createdByUser: Type.Ref(userSchema)

    updatedAt: Type.Optional(Type.String({ format: 'date-time' })),
    createdAt: Type.Optional(Type.String({ format: 'date-time' })),
    updatedById: Type.Optional(Type.Number()),
    createdById: Type.Optional(Type.Number())
  },
  { $id: 'NaturalResource', additionalProperties: false }
)

export type NaturalResource = Static<typeof naturalResourceSchema>

// generate fake data
export function generateFake(user: User) {
  const result = {
    name: faker.lorem.words(3),
    zone: `${faker.location.latitude()}, ${faker.location.longitude()}`,
    dimension: JSON.stringify(faker.number.int(100)),
    amount: faker.number.int(100),
    images: [],
    description: faker.lorem.paragraph()
  }
  logger.debug(`fake data natural resource generated: ${JSON.stringify(result)}`)
  return result
}

export const naturalResourceValidator = getValidator(naturalResourceSchema, dataValidator)
export const naturalResourceResolver = resolve<NaturalResource, HookContext>({
  // createdByUser: virtual(async (message, context) => {
  //   // Associate the user that sent the message
  //   if (message.createdById) {
  //     return context.app.service('users').get(message.createdById)
  //   }
  // }),
  // updatedByUser: virtual(async (message, context) => {
  //   // Associate the user that sent the message
  //   if (message.updatedById) {
  //     return context.app.service('users').get(context.data?.updatedById)
  //   }
  // })
})

export const naturalResourceExternalResolver = resolve<NaturalResource, HookContext>({})

// Schema for creating new entries
export const naturalResourceDataSchema = Type.Pick(
  naturalResourceSchema,
  ['name', 'zone', 'dimension', 'amount', 'images', 'description'],
  {
    $id: 'NaturalResourceData'
  }
)
export type NaturalResourceData = Static<typeof naturalResourceDataSchema>
export const naturalResourceDataValidator = getValidator(naturalResourceDataSchema, dataValidator)
export const naturalResourceDataResolver = resolve<NaturalResource, HookContext>({
  createdAt: virtual(async () => {
    return new Date().toISOString()
  }),
  createdById: virtual(async (message, context) => {
    // Associate the user that sent the message
    return context?.params?.user?.id
  })
})

// Schema for updating existing entries
export const naturalResourcePatchSchema = Type.Partial(naturalResourceSchema, {
  $id: 'NaturalResourcePatch'
})
export type NaturalResourcePatch = Static<typeof naturalResourcePatchSchema>
export const naturalResourcePatchValidator = getValidator(naturalResourcePatchSchema, dataValidator)
export const naturalResourcePatchResolver = resolve<NaturalResource, HookContext>({
  updatedAt: virtual(async () => {
    return new Date().toISOString()
  }),
  updatedById: virtual(async (message, context) => {
    // Associate the user that sent the message
    return context?.params?.user?.id
  })
})

// Schema for allowed query properties
export const naturalResourceQueryProperties = Type.Pick(naturalResourceSchema, ['id', 'name', 'amount'])
export const naturalResourceQuerySchema = Type.Intersect(
  [
    querySyntax(naturalResourceQueryProperties, {
      name: {
        $ilike: Type.String()
      }
    }),
    // Add additional query properties here
    Type.Object({}, { additionalProperties: true })
  ],
  { additionalProperties: true }
)
export type NaturalResourceQuery = Static<typeof naturalResourceQuerySchema>
export const naturalResourceQueryValidator = getValidator(naturalResourceQuerySchema, queryValidator)
export const naturalResourceQueryResolver = resolve<NaturalResourceQuery, HookContext>({
  // createdByUser: virtual(async (message, context) => {
  //   // Associate the user that sent the message
  //   return context.app.service('users').get(message.createdById)
  // }),
  // updatedByUser: virtual(async (message, context) => {
  //   // Associate the user that sent the message
  //   if (message.updatedById) {
  //     return context.app.service('users').get(context.data?.updatedById)
  //   }
  // })
})
