// // For more information about this file see https://dove.feathersjs.com/guides/cli/service.schemas.html
import { resolve } from '@feathersjs/schema'
import { Type, getValidator, querySyntax } from '@feathersjs/typebox'
import type { Static } from '@feathersjs/typebox'

import type { HookContext } from '../../declarations'
import { dataValidator, queryValidator } from '../../validators'
import { userSchema } from '../users/users.schema'

// Main data model schema
export const professionalSchema = Type.Object(
  {
    id: Type.Number(),
    updatedAt: Type.Optional(Type.String({ format: 'date-time' })),
    createAt: Type.String({ format: 'date-time' }),
    updatedById: Type.Optional(Type.Number()),
    createdById: Type.Number(),

    name: Type.String({ minLength: 1 }),
    description: Type.String(),
    address: Type.String({ minLength: 1 }),
    images: Type.Array(Type.String()), // url

    // generated by the resolver
    updatedByUser: Type.Ref(userSchema),
    createdByUser: Type.Ref(userSchema)
  },
  { $id: 'Professional', additionalProperties: false }
)
export type Professional = Static<typeof professionalSchema>
export const professionalValidator = getValidator(professionalSchema, dataValidator)
export const professionalResolver = resolve<Professional, HookContext>({})

export const professionalExternalResolver = resolve<Professional, HookContext>({})

// Schema for creating new entries
export const professionalDataSchema = Type.Pick(professionalSchema, ['description'], {
  $id: 'ProfessionalData'
})
export type ProfessionalData = Static<typeof professionalDataSchema>
export const professionalDataValidator = getValidator(professionalDataSchema, dataValidator)
export const professionalDataResolver = resolve<Professional, HookContext>({})

// Schema for updating existing entries
export const professionalPatchSchema = Type.Partial(professionalSchema, {
  $id: 'ProfessionalPatch'
})
export type ProfessionalPatch = Static<typeof professionalPatchSchema>
export const professionalPatchValidator = getValidator(professionalPatchSchema, dataValidator)
export const professionalPatchResolver = resolve<Professional, HookContext>({})

// Schema for allowed query properties
export const professionalQueryProperties = Type.Pick(professionalSchema, ['id', 'description'])
export const professionalQuerySchema = Type.Intersect(
  [
    querySyntax(professionalQueryProperties),
    // Add additional query properties here
    Type.Object({}, { additionalProperties: false })
  ],
  { additionalProperties: false }
)
export type ProfessionalQuery = Static<typeof professionalQuerySchema>
export const professionalQueryValidator = getValidator(professionalQuerySchema, queryValidator)
export const professionalQueryResolver = resolve<ProfessionalQuery, HookContext>({})
