// // For more information about this file see https://dove.feathersjs.com/guides/cli/service.schemas.html
import { resolve } from '@feathersjs/schema'
import { Type, getValidator, querySyntax } from '@feathersjs/typebox'
import type { Static } from '@feathersjs/typebox'

import type { HookContext } from '../../declarations'
import { dataValidator, queryValidator } from '../../validators'
import { User, userSchema } from '../users/users.schema'
import { logger } from '../../logger'
import { faker } from '@faker-js/faker'

// Main data model schema
export const professionalSchema = Type.Object(
  {
    id: Type.Number(),
    updatedAt: Type.Optional(Type.String({ format: 'date-time' })),
    createdAt: Type.String({ format: 'date-time' }),
    updatedById: Type.Optional(Type.Number()),
    createdById: Type.Number(),

    name: Type.String({ minLength: 1 }),
    description: Type.String(),
    address: Type.String({ minLength: 1 }),
    images: Type.Array(Type.String()), // url

    // generated by the resolver
    updatedByUser: Type.Optional(Type.Ref(userSchema)),
    createdByUser: Type.Ref(userSchema)
  },
  { $id: 'Professional', additionalProperties: true }
)
export type Professional = Static<typeof professionalSchema>



// generate fake data
export async function generateFake(user: User) {
  // const findUser = app_.find()
  logger.info(`fake USER building generated: ${JSON.stringify(user.id)}`);
  const result = ({
    updatedById: user.id,
    createdById: user.id,

    name: faker.lorem.words(3),
    description: faker.lorem.paragraph(),
    address: faker.location.streetAddress(),
    images: [],

  });
  // logger.info(`fake data building generated: ${JSON.stringify(result)}`)
  return result;
}

export const professionalValidator = getValidator(professionalSchema, dataValidator)
export const professionalResolver = resolve<Professional, HookContext>({})

export const professionalExternalResolver = resolve<Professional, HookContext>({})

// Schema for creating new entries
export const professionalDataSchema = Type.Pick(professionalSchema, ['name', 'description', 'address', 'images'], {
  $id: 'ProfessionalData'
})
export type ProfessionalData = Static<typeof professionalDataSchema>
export const professionalDataValidator = getValidator(professionalDataSchema, dataValidator)
export const professionalDataResolver = resolve<Professional, HookContext>({})

// Schema for updating existing entries
export const professionalPatchSchema = Type.Partial(professionalSchema, {
  $id: 'ProfessionalPatch'
})
export type ProfessionalPatch = Static<typeof professionalPatchSchema>
export const professionalPatchValidator = getValidator(professionalPatchSchema, dataValidator)
export const professionalPatchResolver = resolve<Professional, HookContext>({})

// Schema for allowed query properties
export const professionalQueryProperties = Type.Pick(professionalSchema, ['id', 'description'])
export const professionalQuerySchema = Type.Intersect(
  [
    querySyntax(professionalQueryProperties),
    // Add additional query properties here
    Type.Object({}, { additionalProperties: false })
  ],
  { additionalProperties: false }
)
export type ProfessionalQuery = Static<typeof professionalQuerySchema>
export const professionalQueryValidator = getValidator(professionalQuerySchema, queryValidator)
export const professionalQueryResolver = resolve<ProfessionalQuery, HookContext>({})
