"""building_material_types

Revision ID: e1c96da74747
Revises: 6da44370c86f
Create Date: 2024-12-04 13:17:23.155463

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'e1c96da74747'
down_revision: Union[str, None] = '6da44370c86f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('buildingmaterial', sa.Column(
        'types', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.drop_column('buildingmaterial', 'type')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('buildingmaterial', sa.Column(
        'type', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.drop_column('buildingmaterial', 'types')
    # ### end Alembic commands ###
