"""building-fields

Revision ID: 86ee029f0372
Revises: e1c96da74747
Create Date: 2024-12-16 16:23:30.967148

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '86ee029f0372'
down_revision: Union[str, None] = 'e1c96da74747'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('building', sa.Column(
        'client', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('building', sa.Column(
        'gross_internal_area', sa.Float(), nullable=True))
    op.add_column('building', sa.Column('year', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('building', 'year')
    op.drop_column('building', 'gross_internal_area')
    op.drop_column('building', 'client')
    # ### end Alembic commands ###
