"""fire-low-high

Revision ID: 659fc00a69fa
Revises: 9dd17a356a73
Create Date: 2024-12-18 09:52:55.635120

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '659fc00a69fa'
down_revision: Union[str, None] = '9dd17a356a73'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('buildingmaterial', sa.Column(
        'reaction_to_fire_low', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('buildingmaterial', sa.Column(
        'fire_resistance_class_low', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('buildingmaterial', sa.Column(
        'reaction_to_fire_high', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('buildingmaterial', sa.Column(
        'fire_resistance_class_high', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('naturalresource', sa.Column(
        'reaction_to_fire_low', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('naturalresource', sa.Column(
        'fire_resistance_class_low', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('naturalresource', sa.Column(
        'reaction_to_fire_high', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('naturalresource', sa.Column(
        'fire_resistance_class_high', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('technicalconstruction', sa.Column(
        'reaction_to_fire_low', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('technicalconstruction', sa.Column(
        'fire_resistance_class_low', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('technicalconstruction', sa.Column(
        'reaction_to_fire_high', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('technicalconstruction', sa.Column(
        'fire_resistance_class_high', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('technicalconstruction', 'fire_resistance_class_high')
    op.drop_column('technicalconstruction', 'reaction_to_fire_high')
    op.drop_column('technicalconstruction', 'fire_resistance_class_low')
    op.drop_column('technicalconstruction', 'reaction_to_fire_low')
    op.drop_column('naturalresource', 'fire_resistance_class_high')
    op.drop_column('naturalresource', 'reaction_to_fire_high')
    op.drop_column('naturalresource', 'fire_resistance_class_low')
    op.drop_column('naturalresource', 'reaction_to_fire_low')
    op.drop_column('buildingmaterial', 'fire_resistance_class_high')
    op.drop_column('buildingmaterial', 'reaction_to_fire_high')
    op.drop_column('buildingmaterial', 'fire_resistance_class_low')
    op.drop_column('buildingmaterial', 'reaction_to_fire_low')
    # ### end Alembic commands ###
