"""fire_classes

Revision ID: b4c9810eb40b
Revises: 0081d7a95016
Create Date: 2024-12-03 09:38:19.527517

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'b4c9810eb40b'
down_revision: Union[str, None] = '0081d7a95016'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('buildingmaterial', 'reaction_to_fire',
                    existing_type=sa.Float(),
                    type_=sqlmodel.sql.sqltypes.AutoString(),
                    existing_nullable=True)
    op.alter_column('buildingmaterial', 'building_material_class',
                    existing_type=sa.Float(),
                    type_=sqlmodel.sql.sqltypes.AutoString(),
                    existing_nullable=True)
    op.alter_column('buildingmaterial', 'fire_resistance_class',
                    existing_type=sa.Float(),
                    type_=sqlmodel.sql.sqltypes.AutoString(),
                    existing_nullable=True)
    op.drop_column('buildingmaterial', 'fire_resistance_class_high')
    op.drop_column('buildingmaterial', 'reaction_to_fire_high')
    op.drop_column('buildingmaterial', 'reaction_to_fire_low')
    op.drop_column('buildingmaterial', 'building_material_class_low')
    op.drop_column('buildingmaterial', 'building_material_class_high')
    op.drop_column('buildingmaterial', 'fire_resistance_class_low')
    op.alter_column('naturalresource', 'reaction_to_fire',
                    existing_type=sa.Float(),
                    type_=sqlmodel.sql.sqltypes.AutoString(),
                    existing_nullable=True)
    op.alter_column('naturalresource', 'building_material_class',
                    existing_type=sa.Float(),
                    type_=sqlmodel.sql.sqltypes.AutoString(),
                    existing_nullable=True)
    op.alter_column('naturalresource', 'fire_resistance_class',
                    existing_type=sa.Float(),
                    type_=sqlmodel.sql.sqltypes.AutoString(),
                    existing_nullable=True)
    op.drop_column('naturalresource', 'fire_resistance_class_high')
    op.drop_column('naturalresource', 'reaction_to_fire_high')
    op.drop_column('naturalresource', 'reaction_to_fire_low')
    op.drop_column('naturalresource', 'building_material_class_low')
    op.drop_column('naturalresource', 'building_material_class_high')
    op.drop_column('naturalresource', 'fire_resistance_class_low')
    op.alter_column('technicalconstruction', 'reaction_to_fire',
                    existing_type=sa.Float(),
                    type_=sqlmodel.sql.sqltypes.AutoString(),
                    existing_nullable=True)
    op.alter_column('technicalconstruction', 'building_material_class',
                    existing_type=sa.Float(),
                    type_=sqlmodel.sql.sqltypes.AutoString(),
                    existing_nullable=True)
    op.alter_column('technicalconstruction', 'fire_resistance_class',
                    existing_type=sa.Float(),
                    type_=sqlmodel.sql.sqltypes.AutoString(),
                    existing_nullable=True)
    op.drop_column('technicalconstruction', 'fire_resistance_class_high')
    op.drop_column('technicalconstruction', 'reaction_to_fire_high')
    op.drop_column('technicalconstruction', 'reaction_to_fire_low')
    op.drop_column('technicalconstruction', 'building_material_class_low')
    op.drop_column('technicalconstruction', 'building_material_class_high')
    op.drop_column('technicalconstruction', 'fire_resistance_class_low')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('technicalconstruction', sa.Column('fire_resistance_class_low',
                  sa.Float(), autoincrement=False, nullable=True))
    op.add_column('technicalconstruction', sa.Column('building_material_class_high',
                  sa.Float(), autoincrement=False, nullable=True))
    op.add_column('technicalconstruction', sa.Column('building_material_class_low',
                  sa.Float(), autoincrement=False, nullable=True))
    op.add_column('technicalconstruction', sa.Column('reaction_to_fire_low',
                  sa.Float(), autoincrement=False, nullable=True))
    op.add_column('technicalconstruction', sa.Column('reaction_to_fire_high',
                  sa.Float(), autoincrement=False, nullable=True))
    op.add_column('technicalconstruction', sa.Column('fire_resistance_class_high',
                  sa.Float(), autoincrement=False, nullable=True))
    op.execute("""
        ALTER TABLE technicalconstruction 
        ALTER COLUMN fire_resistance_class TYPE DOUBLE PRECISION 
        USING fire_resistance_class::DOUBLE PRECISION
    """)
    op.alter_column(
        "technicalconstruction",
        "fire_resistance_class",
        existing_nullable=True
    )
    op.execute("""
        ALTER TABLE technicalconstruction 
        ALTER COLUMN building_material_class TYPE DOUBLE PRECISION 
        USING building_material_class::DOUBLE PRECISION
    """)
    op.alter_column(
        "technicalconstruction",
        "building_material_class",
        existing_nullable=True
    )
    op.execute("""
        ALTER TABLE technicalconstruction 
        ALTER COLUMN reaction_to_fire TYPE DOUBLE PRECISION 
        USING reaction_to_fire::DOUBLE PRECISION
    """)
    op.alter_column(
        "technicalconstruction",
        "reaction_to_fire",
        existing_nullable=True
    )
    op.add_column('naturalresource', sa.Column('fire_resistance_class_low',
                  sa.Float(), autoincrement=False, nullable=True))
    op.add_column('naturalresource', sa.Column('building_material_class_high',
                  sa.Float(), autoincrement=False, nullable=True))
    op.add_column('naturalresource', sa.Column('building_material_class_low',
                  sa.Float(), autoincrement=False, nullable=True))
    op.add_column('naturalresource', sa.Column('reaction_to_fire_low',
                  sa.Float(), autoincrement=False, nullable=True))
    op.add_column('naturalresource', sa.Column('reaction_to_fire_high',
                  sa.Float(), autoincrement=False, nullable=True))
    op.add_column('naturalresource', sa.Column('fire_resistance_class_high',
                  sa.Float(), autoincrement=False, nullable=True))
    op.execute("""
        ALTER TABLE naturalresource 
        ALTER COLUMN fire_resistance_class TYPE DOUBLE PRECISION 
        USING fire_resistance_class::DOUBLE PRECISION
    """)
    op.alter_column(
        "naturalresource",
        "fire_resistance_class",
        existing_nullable=True
    )
    op.execute("""
        ALTER TABLE naturalresource 
        ALTER COLUMN building_material_class TYPE DOUBLE PRECISION 
        USING building_material_class::DOUBLE PRECISION
    """)
    op.alter_column(
        "naturalresource",
        "building_material_class",
        existing_nullable=True
    )
    op.execute("""
        ALTER TABLE naturalresource 
        ALTER COLUMN reaction_to_fire TYPE DOUBLE PRECISION 
        USING reaction_to_fire::DOUBLE PRECISION
    """)
    op.alter_column(
        "naturalresource",
        "reaction_to_fire",
        existing_nullable=True
    )
    op.add_column('buildingmaterial', sa.Column('fire_resistance_class_low',
                  sa.Float(), autoincrement=False, nullable=True))
    op.add_column('buildingmaterial', sa.Column('building_material_class_high',
                  sa.Float(), autoincrement=False, nullable=True))
    op.add_column('buildingmaterial', sa.Column('building_material_class_low',
                  sa.Float(), autoincrement=False, nullable=True))
    op.add_column('buildingmaterial', sa.Column('reaction_to_fire_low',
                  sa.Float(), autoincrement=False, nullable=True))
    op.add_column('buildingmaterial', sa.Column('reaction_to_fire_high',
                  sa.Float(), autoincrement=False, nullable=True))
    op.add_column('buildingmaterial', sa.Column('fire_resistance_class_high',
                  sa.Float(), autoincrement=False, nullable=True))
    op.execute("""
        ALTER TABLE buildingmaterial 
        ALTER COLUMN fire_resistance_class TYPE DOUBLE PRECISION 
        USING fire_resistance_class::DOUBLE PRECISION
    """)
    op.alter_column(
        "buildingmaterial",
        "fire_resistance_class",
        existing_nullable=True
    )
    op.execute("""
        ALTER TABLE buildingmaterial 
        ALTER COLUMN building_material_class TYPE DOUBLE PRECISION 
        USING building_material_class::DOUBLE PRECISION
    """)
    op.alter_column(
        "buildingmaterial",
        "building_material_class",
        existing_nullable=True
    )
    op.execute("""
        ALTER TABLE buildingmaterial 
        ALTER COLUMN reaction_to_fire TYPE DOUBLE PRECISION 
        USING reaction_to_fire::DOUBLE PRECISION
    """)
    op.alter_column(
        "buildingmaterial",
        "reaction_to_fire",
        existing_nullable=True
    )
    # ### end Alembic commands ###
