"""building_elements

Revision ID: 6da44370c86f
Revises: b4c9810eb40b
Create Date: 2024-12-03 12:48:43.569247

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6da44370c86f'
down_revision: Union[str, None] = 'b4c9810eb40b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('buildingelement',
                    sa.Column('building_id', sa.Integer(), nullable=True),
                    sa.Column('technical_construction_id',
                              sa.Integer(), nullable=True),
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(
                        ['building_id'], ['building.id'], ondelete='CASCADE'),
                    sa.ForeignKeyConstraint(['technical_construction_id'], [
                        'technicalconstruction.id'], ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_buildingelement_id'),
                    'buildingelement', ['id'], unique=False)
    op.create_table('buildingelementprofessional',
                    sa.Column('building_element_id',
                              sa.Integer(), nullable=False),
                    sa.Column('professional_id', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(['building_element_id'], [
                        'buildingelement.id'], ),
                    sa.ForeignKeyConstraint(['professional_id'], [
                                            'professional.id'], ),
                    sa.PrimaryKeyConstraint(
                        'building_element_id', 'professional_id')
                    )
    op.drop_table('buildingtechnicalconstruction')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('buildingtechnicalconstruction',
                    sa.Column('building_id', sa.INTEGER(),
                              autoincrement=False, nullable=False),
                    sa.Column('technical_construction_id', sa.INTEGER(),
                              autoincrement=False, nullable=False),
                    sa.ForeignKeyConstraint(['building_id'], [
                        'building.id'], name='buildingtechnicalconstruction_building_id_fkey'),
                    sa.ForeignKeyConstraint(['technical_construction_id'], [
                        'technicalconstruction.id'], name='buildingtechnicalconstruction_technical_construction_id_fkey'),
                    sa.PrimaryKeyConstraint(
                        'building_id', 'technical_construction_id', name='buildingtechnicalconstruction_pkey')
                    )
    op.drop_table('buildingelementprofessional')
    op.drop_index(op.f('ix_buildingelement_id'), table_name='buildingelement')
    op.drop_table('buildingelement')
    # ### end Alembic commands ###
