"""fire

Revision ID: 9dd17a356a73
Revises: 86ee029f0372
Create Date: 2024-12-16 17:07:53.953740

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9dd17a356a73'
down_revision: Union[str, None] = '86ee029f0372'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('buildingmaterial', 'building_material_class')
    op.drop_column('naturalresource', 'building_material_class')
    op.drop_column('technicalconstruction', 'building_material_class')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('technicalconstruction', sa.Column('building_material_class', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('naturalresource', sa.Column('building_material_class', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('buildingmaterial', sa.Column('building_material_class', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
