"""assignee

Revision ID: 60a1a32c263a
Revises: f1ef88b72cc3
Create Date: 2025-08-18 11:08:14.710323

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '60a1a32c263a'
down_revision: Union[str, None] = 'f1ef88b72cc3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('building', sa.Column(
        'assigned_at', sa.DateTime(), nullable=True))
    op.add_column('building', sa.Column(
        'assigned_to', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('buildingmaterial', sa.Column(
        'assigned_at', sa.DateTime(), nullable=True))
    op.add_column('buildingmaterial', sa.Column(
        'assigned_to', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('naturalresource', sa.Column(
        'assigned_at', sa.DateTime(), nullable=True))
    op.add_column('naturalresource', sa.Column(
        'assigned_to', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('professional', sa.Column(
        'assigned_at', sa.DateTime(), nullable=True))
    op.add_column('professional', sa.Column(
        'assigned_to', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('technicalconstruction', sa.Column(
        'assigned_at', sa.DateTime(), nullable=True))
    op.add_column('technicalconstruction', sa.Column(
        'assigned_to', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('technicalconstruction', 'assigned_to')
    op.drop_column('technicalconstruction', 'assigned_at')
    op.drop_column('professional', 'assigned_to')
    op.drop_column('professional', 'assigned_at')
    op.drop_column('naturalresource', 'assigned_to')
    op.drop_column('naturalresource', 'assigned_at')
    op.drop_column('buildingmaterial', 'assigned_to')
    op.drop_column('buildingmaterial', 'assigned_at')
    op.drop_column('building', 'assigned_to')
    op.drop_column('building', 'assigned_at')
    # ### end Alembic commands ###
