"""publication

Revision ID: 756979688f45
Revises: f179385828f6
Create Date: 2025-02-13 11:12:15.492887

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '756979688f45'
down_revision: Union[str, None] = 'f179385828f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('building', sa.Column(
        'published_at', sa.DateTime(), nullable=True))
    op.add_column('building', sa.Column('published_by',
                  sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('buildingmaterial', sa.Column(
        'published_at', sa.DateTime(), nullable=True))
    op.add_column('buildingmaterial', sa.Column('published_by',
                  sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('naturalresource', sa.Column(
        'published_at', sa.DateTime(), nullable=True))
    op.add_column('naturalresource', sa.Column('published_by',
                  sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('professional', sa.Column(
        'published_at', sa.DateTime(), nullable=True))
    op.add_column('professional', sa.Column('published_by',
                  sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('technicalconstruction', sa.Column(
        'published_at', sa.DateTime(), nullable=True))
    op.add_column('technicalconstruction', sa.Column(
        'published_by', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('technicalconstruction', 'published_by')
    op.drop_column('technicalconstruction', 'published_at')
    op.drop_column('professional', 'published_by')
    op.drop_column('professional', 'published_at')
    op.drop_column('naturalresource', 'published_by')
    op.drop_column('naturalresource', 'published_at')
    op.drop_column('buildingmaterial', 'published_by')
    op.drop_column('buildingmaterial', 'published_at')
    op.drop_column('building', 'published_by')
    op.drop_column('building', 'published_at')
    # ### end Alembic commands ###
