"""physics

Revision ID: 08f8606ee04b
Revises: 659fc00a69fa
Create Date: 2025-01-14 09:38:33.694617

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '08f8606ee04b'
down_revision: Union[str, None] = '659fc00a69fa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('buildingmaterial', sa.Column('porosity', sa.Float(), nullable=True))
    op.add_column('buildingmaterial', sa.Column('liquid_transfer_coefficient', sa.Float(), nullable=True))
    op.add_column('buildingmaterial', sa.Column('porosity_low', sa.Float(), nullable=True))
    op.add_column('buildingmaterial', sa.Column('liquid_transfer_coefficient_low', sa.Float(), nullable=True))
    op.add_column('buildingmaterial', sa.Column('porosity_high', sa.Float(), nullable=True))
    op.add_column('buildingmaterial', sa.Column('liquid_transfer_coefficient_high', sa.Float(), nullable=True))
    op.add_column('naturalresource', sa.Column('porosity', sa.Float(), nullable=True))
    op.add_column('naturalresource', sa.Column('liquid_transfer_coefficient', sa.Float(), nullable=True))
    op.add_column('naturalresource', sa.Column('porosity_low', sa.Float(), nullable=True))
    op.add_column('naturalresource', sa.Column('liquid_transfer_coefficient_low', sa.Float(), nullable=True))
    op.add_column('naturalresource', sa.Column('porosity_high', sa.Float(), nullable=True))
    op.add_column('naturalresource', sa.Column('liquid_transfer_coefficient_high', sa.Float(), nullable=True))
    op.add_column('technicalconstruction', sa.Column('porosity', sa.Float(), nullable=True))
    op.add_column('technicalconstruction', sa.Column('liquid_transfer_coefficient', sa.Float(), nullable=True))
    op.add_column('technicalconstruction', sa.Column('porosity_low', sa.Float(), nullable=True))
    op.add_column('technicalconstruction', sa.Column('liquid_transfer_coefficient_low', sa.Float(), nullable=True))
    op.add_column('technicalconstruction', sa.Column('porosity_high', sa.Float(), nullable=True))
    op.add_column('technicalconstruction', sa.Column('liquid_transfer_coefficient_high', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('technicalconstruction', 'liquid_transfer_coefficient_high')
    op.drop_column('technicalconstruction', 'porosity_high')
    op.drop_column('technicalconstruction', 'liquid_transfer_coefficient_low')
    op.drop_column('technicalconstruction', 'porosity_low')
    op.drop_column('technicalconstruction', 'liquid_transfer_coefficient')
    op.drop_column('technicalconstruction', 'porosity')
    op.drop_column('naturalresource', 'liquid_transfer_coefficient_high')
    op.drop_column('naturalresource', 'porosity_high')
    op.drop_column('naturalresource', 'liquid_transfer_coefficient_low')
    op.drop_column('naturalresource', 'porosity_low')
    op.drop_column('naturalresource', 'liquid_transfer_coefficient')
    op.drop_column('naturalresource', 'porosity')
    op.drop_column('buildingmaterial', 'liquid_transfer_coefficient_high')
    op.drop_column('buildingmaterial', 'porosity_high')
    op.drop_column('buildingmaterial', 'liquid_transfer_coefficient_low')
    op.drop_column('buildingmaterial', 'porosity_low')
    op.drop_column('buildingmaterial', 'liquid_transfer_coefficient')
    op.drop_column('buildingmaterial', 'porosity')
    # ### end Alembic commands ###
