"""pro_addresses

Revision ID: d5618e31618b
Revises: 08f8606ee04b
Create Date: 2025-01-16 11:17:45.144645

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd5618e31618b'
down_revision: Union[str, None] = '08f8606ee04b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('professional', sa.Column('addresses', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('professional', 'addresses')
    # ### end Alembic commands ###
