"""be_materials

Revision ID: f179385828f6
Revises: d5618e31618b
Create Date: 2025-01-23 15:16:24.931238

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f179385828f6'
down_revision: Union[str, None] = 'd5618e31618b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('buildingelementmaterial',
    sa.Column('distance', sa.Float(), nullable=True),
    sa.Column('weight', sa.Float(), nullable=True),
    sa.Column('building_element_id', sa.Integer(), nullable=True),
    sa.Column('building_material_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['building_element_id'], ['buildingelement.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['building_material_id'], ['buildingmaterial.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_buildingelementmaterial_id'), 'buildingelementmaterial', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_buildingelementmaterial_id'), table_name='buildingelementmaterial')
    op.drop_table('buildingelementmaterial')
    # ### end Alembic commands ###
