"""pro_pro

Revision ID: abef46517fc1
Revises: 60a1a32c263a
Create Date: 2025-12-08 16:56:36.308101

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'abef46517fc1'
down_revision: Union[str, None] = '60a1a32c263a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('professionalprofessional',
                    sa.Column('professional_id', sa.Integer(), nullable=False),
                    sa.Column('related_id', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(['professional_id'], [
                                            'professional.id'], ),
                    sa.ForeignKeyConstraint(
                        ['related_id'], ['professional.id'], ),
                    sa.PrimaryKeyConstraint('professional_id', 'related_id')
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('professionalprofessional')
    # ### end Alembic commands ###
