"""acls

Revision ID: d0c5ce934d9b
Revises: cbd24d2db43d
Create Date: 2025-07-28 15:13:39.043864

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'd0c5ce934d9b'
down_revision: Union[str, None] = 'cbd24d2db43d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('acl',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column(
                        'resource', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
                    sa.Column('subject_type', sqlmodel.sql.sqltypes.AutoString(),
                              nullable=False),
                    sa.Column(
                        'subject', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
                    sa.Column('permission', sqlmodel.sql.sqltypes.AutoString(),
                              nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('acl')
    # ### end Alembic commands ###
