"""entity_state

Revision ID: f1ef88b72cc3
Revises: d0c5ce934d9b
Create Date: 2025-07-28 19:19:10.770169

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'f1ef88b72cc3'
down_revision: Union[str, None] = 'd0c5ce934d9b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('building', sa.Column(
        'state', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('buildingmaterial', sa.Column(
        'state', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('naturalresource', sa.Column(
        'state', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('professional', sa.Column(
        'state', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('technicalconstruction', sa.Column(
        'state', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # set default values
    op.execute("UPDATE building SET state='draft' WHERE state IS NULL")
    op.execute("UPDATE buildingmaterial SET state='draft' WHERE state IS NULL")
    op.execute("UPDATE naturalresource SET state='draft' WHERE state IS NULL")
    op.execute("UPDATE professional SET state='draft' WHERE state IS NULL")
    op.execute(
        "UPDATE technicalconstruction SET state='draft' WHERE state IS NULL")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('technicalconstruction', 'state')
    op.drop_column('professional', 'state')
    op.drop_column('naturalresource', 'state')
    op.drop_column('buildingmaterial', 'state')
    op.drop_column('building', 'state')
    # ### end Alembic commands ###
