"""water_content_free_saturation

Revision ID: cbd24d2db43d
Revises: 756979688f45
Create Date: 2025-06-12 16:54:07.051849

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cbd24d2db43d'
down_revision: Union[str, None] = '756979688f45'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('buildingmaterial', sa.Column(
        'water_content', sa.Float(), nullable=True))
    op.add_column('buildingmaterial', sa.Column(
        'free_saturation', sa.Float(), nullable=True))
    op.add_column('buildingmaterial', sa.Column(
        'water_content_low', sa.Float(), nullable=True))
    op.add_column('buildingmaterial', sa.Column(
        'free_saturation_low', sa.Float(), nullable=True))
    op.add_column('buildingmaterial', sa.Column(
        'water_content_high', sa.Float(), nullable=True))
    op.add_column('buildingmaterial', sa.Column(
        'free_saturation_high', sa.Float(), nullable=True))
    op.add_column('naturalresource', sa.Column(
        'water_content', sa.Float(), nullable=True))
    op.add_column('naturalresource', sa.Column(
        'free_saturation', sa.Float(), nullable=True))
    op.add_column('naturalresource', sa.Column(
        'water_content_low', sa.Float(), nullable=True))
    op.add_column('naturalresource', sa.Column(
        'free_saturation_low', sa.Float(), nullable=True))
    op.add_column('naturalresource', sa.Column(
        'water_content_high', sa.Float(), nullable=True))
    op.add_column('naturalresource', sa.Column(
        'free_saturation_high', sa.Float(), nullable=True))
    op.add_column('technicalconstruction', sa.Column(
        'water_content', sa.Float(), nullable=True))
    op.add_column('technicalconstruction', sa.Column(
        'free_saturation', sa.Float(), nullable=True))
    op.add_column('technicalconstruction', sa.Column(
        'water_content_low', sa.Float(), nullable=True))
    op.add_column('technicalconstruction', sa.Column(
        'free_saturation_low', sa.Float(), nullable=True))
    op.add_column('technicalconstruction', sa.Column(
        'water_content_high', sa.Float(), nullable=True))
    op.add_column('technicalconstruction', sa.Column(
        'free_saturation_high', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('technicalconstruction', 'free_saturation_high')
    op.drop_column('technicalconstruction', 'water_content_high')
    op.drop_column('technicalconstruction', 'free_saturation_low')
    op.drop_column('technicalconstruction', 'water_content_low')
    op.drop_column('technicalconstruction', 'free_saturation')
    op.drop_column('technicalconstruction', 'water_content')
    op.drop_column('naturalresource', 'free_saturation_high')
    op.drop_column('naturalresource', 'water_content_high')
    op.drop_column('naturalresource', 'free_saturation_low')
    op.drop_column('naturalresource', 'water_content_low')
    op.drop_column('naturalresource', 'free_saturation')
    op.drop_column('naturalresource', 'water_content')
    op.drop_column('buildingmaterial', 'free_saturation_high')
    op.drop_column('buildingmaterial', 'water_content_high')
    op.drop_column('buildingmaterial', 'free_saturation_low')
    op.drop_column('buildingmaterial', 'water_content_low')
    op.drop_column('buildingmaterial', 'free_saturation')
    op.drop_column('buildingmaterial', 'water_content')
    # ### end Alembic commands ###
