"""subject-profile

Revision ID: cfc373505655
Revises: abef46517fc1
Create Date: 2026-01-30 11:35:56.528461

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'cfc373505655'
down_revision: Union[str, None] = 'abef46517fc1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subjectprofile',
    sa.Column('identifier', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('affiliation', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('web', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subjectprofile_id'), 'subjectprofile', ['id'], unique=False)
    op.create_index(op.f('ix_subjectprofile_identifier'), 'subjectprofile', ['identifier'], unique=False)
    op.create_index(op.f('ix_subjectprofile_name'), 'subjectprofile', ['name'], unique=False)
    op.create_index(op.f('ix_subjectprofile_type'), 'subjectprofile', ['type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_subjectprofile_type'), table_name='subjectprofile')
    op.drop_index(op.f('ix_subjectprofile_name'), table_name='subjectprofile')
    op.drop_index(op.f('ix_subjectprofile_identifier'), table_name='subjectprofile')
    op.drop_index(op.f('ix_subjectprofile_id'), table_name='subjectprofile')
    op.drop_table('subjectprofile')
    # ### end Alembic commands ###
