"""subject-profile

Revision ID: ea2d367a187a
Revises: abef46517fc1
Create Date: 2026-01-28 14:19:57.728507

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'ea2d367a187a'
down_revision: Union[str, None] = 'abef46517fc1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subjectprofile',
                    sa.Column(
                        'type', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
                    sa.Column(
                        'name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
                    sa.Column(
                        'affiliation', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
                    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(),
                              nullable=True),
                    sa.Column(
                        'email', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
                    sa.Column(
                        'web', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_subjectprofile_id'),
                    'subjectprofile', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_subjectprofile_id'), table_name='subjectprofile')
    op.drop_table('subjectprofile')
    # ### end Alembic commands ###
