"""source

Revision ID: 2d69ed1b0380
Revises: e9273af636c3
Create Date: 2026-04-27 09:05:24.707395

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '2d69ed1b0380'
down_revision: Union[str, None] = 'e9273af636c3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('building', sa.Column(
        'source', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('buildingmaterial', sa.Column(
        'source', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('naturalresource', sa.Column(
        'source', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('professional', sa.Column(
        'source', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('technicalconstruction', sa.Column(
        'source', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('technicalconstruction', 'source')
    op.drop_column('professional', 'source')
    op.drop_column('naturalresource', 'source')
    op.drop_column('buildingmaterial', 'source')
    op.drop_column('building', 'source')
    # ### end Alembic commands ###
