"""be-type

Revision ID: e9273af636c3
Revises: 6665458e5de9
Create Date: 2026-02-12 10:21:18.175818

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'e9273af636c3'
down_revision: Union[str, None] = '6665458e5de9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('buildingelement', sa.Column(
        'type', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('buildingelement', 'type')
    # ### end Alembic commands ###
