"""related_sources

Revision ID: 51daafce2796
Revises: 2d69ed1b0380
Create Date: 2026-04-29 18:18:48.421738

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '51daafce2796'
down_revision: Union[str, None] = '2d69ed1b0380'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('building', sa.Column('related_sources',
                  postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('buildingmaterial', sa.Column('related_sources',
                  postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('naturalresource', sa.Column('related_sources',
                  postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('professional', sa.Column('related_sources',
                  postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('technicalconstruction', sa.Column(
        'related_sources', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('technicalconstruction', 'related_sources')
    op.drop_column('professional', 'related_sources')
    op.drop_column('naturalresource', 'related_sources')
    op.drop_column('buildingmaterial', 'related_sources')
    op.drop_column('building', 'related_sources')
    # ### end Alembic commands ###
